### ISSUE TITLE
No highlighting in <style> tags

### ISSUE THREAD

**Issue by nathanfdunn** [natewallace/language-vscode-javascript-angular2#5]
This code is similar to that shown in the [example](https://github.com/natewallace/language-vscode-javascript-angular2/blob/master/images/example.png), but the content in the `<style>` tags does not have highlighting. 

![broken-style-highlighting](https://cloud.githubusercontent.com/assets/4128781/17028377/6675c59c-4f35-11e6-98b1-be612b52fb9d.png)

**Comment by natewallace** [comment]
The style highlighting was accidentally backed out with the update to support comments in version 0.0.9.  I've put the style highlighting back in with version 0.0.10.  Note that the style element will need to be the first element in the template to get highlighting.

Thanks for the bug report.
