### ISSUE TITLE
<br> tags break syntax highlighting

### ISSUE THREAD

**Issue by rjsmith1999** [natewallace/language-vscode-javascript-angular2#6]
Example code:

```
import { Component } from '@angular/core';
@Component({
  selector: 'question',
  template:  `<h2> Question </h2> <br>
              <h3> Answer 1 </h3> <br>
              <h3> Answer 2 </h3> <br>
              <h3> Answer 3 </h3> <br>
              <h3> Answer 4 </h3> <br>
              <h3> Answer 5 </h3> <br>
              <h3> Skip </h3> <br>`
})
export class Question { }
```

**Comment by natewallace** [comment]
I'm not able to duplicate this issue.  I copied your example code into a file and the syntax highlighting appears correctly on my machine.  Can you give me more details about your setup?  What version of vscode are you using(I tested on 1.5.3)?  What version of the extension are you using(I tested with 0.0.11)?

**Comment by natewallace** [comment]
I do have a fix for this however I've been locked out of the account I used to publish this extensions to the vscode marketplace.  As soon as I can get back into my account I should be able to get this fix pushed.  Failing that I may need to create a new account and publish this as a new extension.

**Comment by ValterSantosMatos** [comment]
You can use <br/>

**Comment by natewallace** [comment]
I've fixed this issue but I had to publish it as a new extension.  The new extension replaces this one and it can be found here:
I've published the new extension and it can be found here:
https://marketplace.visualstudio.com/items?itemName=natewallace.angular2-inline
