### ISSUE TITLE
Don't work with latest Typescript grammar

### ISSUE THREAD

**Issue by michaeljota** [natewallace/language-vscode-javascript-angular2#7]
Don't work with the [`Latest Typescript and JavaScript Grammar`](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar). 

I think that will be the default engine for Typescript and JavaScript grammar in the next release, so I think it's important to be updated.

**Comment by mhegazy** [comment]
VSCode 1.7 should be shipping with the updated grammar files next month. For the sources and any issues, use https://github.com/Microsoft/TypeScript-tmlanguage. Please let us know if there are any problems you run into.

**Comment by natewallace** [comment]
This extension grammar is being injected into the meta.block rule.  It doesn't look like that rule has changed from the previous grammar.  I wonder if injections don't work with the 'Latest Typescript' extension like they do with the one that ships with the app.

**Comment by michaeljota** [comment]
Hummm... So I guess that we could wait and found out soon, when Insider start shipping with this new extension.

**Comment by sheetalkamat** [comment]
@natewallace ```meta.block``` is used for statements. You want to inject into ```meta.object-literal```

**Comment by natewallace** [comment]
Oh yeah, your right.  I was comparing the wrong version of the grammar file.

**Comment by linusbrolin** [comment]
@natewallace VSCode 1.7 has been released and the updated grammar does indeed cause this plugin to not work anymore.

**Comment by michaeljota** [comment]
I know that VSCode are going to handle HTML grammar soon in any file type, but in the meant time, it would be useful to still having this available.

**Comment by natewallace** [comment]
I'll try and take a look at this this weekend.

**Comment by AriesMOo** [comment]
This is the most useful extension ever in VSCode... Thanks for your work (I miss the functionality provided)

**Comment by sheetalkamat** [comment]
@natewallace if you enable contribution from me, I can send the PR for it to work with the latest grammar.

**Comment by natewallace** [comment]
Sorry for the delay on this.  Thanks to @sheetalkamat for a PR that has a fix to work with the new typescript grammar.  Unfortunately I am locked out of my VSCode Marketplace account so I won't be able to publish an update to the existing extension.  Later tonight I'm going to create a new account and publish this as a new package.

**Comment by natewallace** [comment]
I've published the new extension and it can be found here:
https://marketplace.visualstudio.com/items?itemName=natewallace.angular2-inline

**Comment by michaeljota** [comment]
It have unknown dependencies. Can't install.

**Comment by natewallace** [comment]
Looks like the extensionDependencies section is no longer needed in the package.json.  I've removed this and re-published the extension.  It should install now.

**Comment by michaeljota** [comment]
I think extensionDependencies it's now about other extensions that this extension depends on. Thanks you. :).
